brew "neovim"
brew "tmux"
brew "starship"
brew "uv"
brew "libpq"
brew "ripgrep"
brew "zsh-autosuggestions"
brew "zsh-syntax-highlighting"
brew "tree-sitter-cli"
brew "lazygit"
brew "node"

cask "ghostty"
cask "rectangle"
cask "sanesidebuttons"
