set -g prefix C-Space
unbind C-b
bind C-Space send-prefix
bind Space last-window

setw -g mode-keys vi
set -g mouse on

bind h select-pane -L
bind j select-pane -D
bind k select-pane -U
bind l select-pane -R

bind -r H resize-pane -L 5
bind -r J resize-pane -D 5
bind -r K resize-pane -U 5
bind -r L resize-pane -R 5

bind -T copy-mode-vi v send -X begin-selection
bind -T copy-mode-vi y send -X copy-selection-and-cancel

bind r source-file ~/.config/tmux/tmux.conf \; display-message "Config reloaded!"

set -g base-index 1
setw -g pane-base-index 1
set -g renumber-windows on

set -g focus-events on

set -g history-limit 50000

set -g status-style "bg=default"
set -g window-status-current-style "bold"
set -g status-justify absolute-centre
set -g status-left ""
set -g status-right ""
